name: Generate Pacman Game

on:
  schedule:
    - cron: "0 0 * * *" # Runs every night
  workflow_dispatch: # Allows you to start it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # This is the specialized Pacman engine
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: shivamtiwari01016
          template: classic
          base: "" 
          # This specific plugin creates the Pac-Man effect
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
