name: Generate Space Pacman

on:
  schedule:
    - cron: "0 0 * * *" # Runs every night
  workflow_dispatch: # Allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - name: generate space-pacman.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: shivamtiwari01016
          # The color_snake is the "Smiley", color_dots are the pellets
          outputs: |
            dist/space-pacman.svg?color_snake=yellow&color_dots=#161b22,#00441b,#006d2c,#26a641,#39d353&palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: push-to-output-branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
