name: Generate Pacman Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Runs every night
  workflow_dispatch: # Allows manual trigger
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: shivamtiwari01016
          template: classic
          base: "" # This hides the default stats so we only get the game
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year # Shows 6 months of maze
